### ISSUE TITLE
Handle "delta" specs in CSS dumps

### ISSUE THREAD

**Issue by tidoust** [tidoust/reffy#117]
Some newer levels of CSS drafts are currently (and temporarily) defined as "delta" specifications. The list includes:

- [CSS Animations Level 2](https://drafts.csswg.org/css-animations-2/#delta)
- [CSS Grid Level 2](https://drafts.csswg.org/css-grid-2/#intro)
- [CSS Transitions Level 2](https://drafts.csswg.org/css-transitions-2/#delta)
- [Filter Effects Level 2](https://drafts.fxtf.org/filter-effects-2/#intro)

The CSS dumps created in the `css` folder are meant to convey the contents of the latest level, but in the case of delta specifications, the latest level does not include the definitions of the previous level, which is a pity.

Consider adding a way to `delta` flag to spec descriptions and to concatenate the definitions of the delta spec with the definitions of the previous level for such specs.

**Comment by dontcallmedom** [comment]
@tidoust is this handled by reffy now that we're tracking that state in browser-specs?

**Comment by tidoust** [comment]
I believe we can close.

With the "delta" info in browser-specs, CSS extracts created by Reffy are those for the full spec. We could easily switch to a model where Reffy produces extracts both for the full spec and the delta spec (using the leveled shortname to name files, as done for definitions) if that seems useful. Pending requests for such a feature, I suggest we just leave it at that for now.

(Merging the full and delta definitions seems more "risky" in that I'm not sure all delta specs merely extend full specs on which they are based)
