### ISSUE TITLE
html.idl has become almost empty

### ISSUE THREAD

**Issue by foolip** [tidoust/reffy#125]
In https://github.com/tidoust/reffy-reports/commit/7a622d9dbc3a8da6c61f76f95943eb90a6271007 the whatwg/idl/html.idl file became almost empty:
https://github.com/tidoust/reffy-reports/blob/7a622d9dbc3a8da6c61f76f95943eb90a6271007/whatwg/idl/html.idl

Looking at https://github.com/whatwg/html/commits/master and https://github.com/whatwg/html-build/commits/master and remains in html.idl now, I suspect some connection to https://github.com/whatwg/html/pull/3677.

@tidoust, are there particulars about how IDL is extracted from HTML that might be causing this?

**Comment by tidoust** [comment]
The IDL extractor was a bit conservative and assumed that a given spec would follow one and only one convention to define IDL. This had worked fine until now.

https://github.com/whatwg/html/pull/3677 introduces IDL definitions with a `<pre class="idl">` convention in the HTML spec, different from the `<pre><code class="idl">` convention used in the rest of the spec. That explains why the IDL extractor got confused.

I made the IDL extractor more flexible. It now tries all patterns. This fixes the issue for the HTML spec and does not change the outcome for all other specs. The `html.idl` file will be updated next time the crawler runs.

**Comment by tidoust** [comment]
IDL extract now back to normal via https://github.com/tidoust/reffy-reports/commit/18044a1bca678fae7b7039234d7e331ef67d81fd

Closing the issue as a result.
