### ISSUE TITLE
Remove example interface from html.idl

### ISSUE THREAD

**Issue by Ms2ger** [tidoust/reffy#129]
https://github.com/tidoust/reffy-reports/blob/3ed6073a7da37d1f6c340153c3844a411f7ed84d/whatwg/idl/html.idl includes

```webidl
[Exposed=Window]
interface Example {
  // this is an IDL definition
};
```

**Comment by foolip** [comment]
@tidoust, https://html.spec.whatwg.org/#typographic-conventions has `class="extract"` and I think the fix would be right around here:
https://github.com/tidoust/reffy/blob/22df46ab90382bab1949be56d8635f9d429066f6/src/cli/extract-webidl.js#L110

I think you'd have to check if the element or any ancestors have the `extract` class, to handle `<pre class=extract><code class=idl>` which is the pattern in HTML.

**Comment by foolip** [comment]
https://github.com/tidoust/reffy/pull/137 seems to not have worked for HTML. But I don't understand why, because the selector 'pre:not(.exclude):not(.extract) > code.idl:not(.exclude):not(.extract)' no longer matches the `code` element in question, but the previous selector did.

**Comment by tidoust** [comment]
Problem is crawl failed on the HTML spec yesterday and today due to some timeout, and Reffy was unable to update the IDL as a result. That happens from time to time. I confirm it will work once the crawl succeeds!

**Comment by tidoust** [comment]
Hmm, the failure seems to repeat itself. We may be hitting a memory limit on the server (crawling the HTML spec seems to require 1.5GB). I need to sync up with @dontcallmedom to investigate what happens.

In the meantime, I updated the IDL extracts manually from a local run of the crawler, and will now close the issue:
https://github.com/tidoust/reffy-reports/commit/5eb5dda4efda33ed74dad82405791e51d9fa8047

**Comment by foolip** [comment]
@tidoust the changes were reverted automatically in https://github.com/tidoust/reffy-reports/commit/cd2862869308107e49f30c94e93756274bdc584a :/

Very suspect is that "partial interface mixin NavigatorID" reverted back to "partial interface NavigatorID" which can't have happened by parsing https://html.spec.whatwg.org/#client-identification, so where is it from?

**Comment by tidoust** [comment]
Argh. Given that the crawler still fails to crawl the HTML spec on the server, I suspect the Git commands run there push the old version of the IDL file... @dontcallmedom ?

**Comment by foolip** [comment]
Sounds related to the "never delete files automatically" setup? If so, shouldn't the starting point be what's already in the repo, and not whatever was left on disk on the server last time?

**Comment by tidoust** [comment]
Good. I re-applied the changes to `html.idl`.
(FWIW, crawl still crashes on this file on the server for now, that's a separate issue)

**Comment by foolip** [comment]
Thanks! https://github.com/web-platform-tests/wpt/pull/14954/files looks good again now.
