### ISSUE TITLE
Consider removing useless leading spaces in IDL dumps

### ISSUE THREAD

**Issue by tidoust** [tidoust/reffy#130]
See https://github.com/web-platform-tests/wpt/pull/13512#issuecomment-429837224

**Comment by foolip** [comment]
@tidoust said in https://github.com/web-platform-tests/wpt/pull/13512#issuecomment-430658440:

> One thing that could be done without parsing would be to remove `n` leading spaces from each line when all lines start with at least `n` spaces. It will work for this netinfo case, but that's just a partial solution: if a spec puts the first line right after a `<pre>` tag without leading spaces, and uses artificial indentation of further lines, the problem would still appear. I'm not sure how to fix the generic case.

@lukebjerring did exactly this with the setup we used before Reffy. It seemed to work well enough. More generically, any whitespace changes at the beginning or end of lines ought to be entirely risk-free. Maybe Web IDL could be reasonably auto-indented by throwing at some indentation tool for another language that just happens to look a bit similar :)

**Comment by tidoust** [comment]
Done with a couple of tweaks. See `trimIdlSpaces` function in https://github.com/tidoust/reffy/blob/master/src/cli/extract-webidl.js#L103

Change will trigger a few cosmetic updates in some IDL files in the next report, but these updates seem actually good to me.
