### ISSUE TITLE
Weird IDL exports produced for SVG

### ISSUE THREAD

**Issue by tidoust** [tidoust/reffy#133]
See https://github.com/web-platform-tests/wpt/pull/14249#issuecomment-442008202

The following IDL seems to come and go, even though that part does not seem to have changed in the SVG spec:

```idl
// must only be implemented in certain implementations
partial interface Document {
  readonly attribute DOMString title;
  readonly attribute DOMString referrer;
  readonly attribute DOMString domain;
  readonly attribute Element? activeElement;
};
```

**Comment by tidoust** [comment]
A few notes.

The offending IDL snippet is marked with an `edit:excludefromidl="true"` attribute in the source, and as such gets excluded from the generated IDL index when the spec is built.

Reffy extracts the IDL index from the single page version of the spec (using the `#idl-index pre' selector). If it ends up with an IDL export that contains the offending snippet, it means it failed to extract the index and rather fell back to extracting individual IDL snippets from the single page version of the spec.

I still do not understand how Reffy can fail to detect the IDL index though. In particular the IDL index is not generated on the fly, the document is essentially static.

**Comment by foolip** [comment]
This happened in https://github.com/web-platform-tests/wpt/pull/16344 again.

**Comment by tidoust** [comment]
But this time (and hopefully, that was the case previously as well), the bug is in the spec itself: the generated draft currently contains the offending "// must only be implemented in certain implementations" snippet in the IDL index at the end of the spec: https://svgwg.org/svg2-draft/single-page.html#chapter-idl

It should not. The code that excludes IDL fragments flagged with "edit:excludefromidl" from the IDL index is at:
https://github.com/w3c/svgwg/blob/master/tools/publish/processing.js#L415

I don't know how we can end up in a situation where this code works half of the time... The issue should be fixed there. In the meantime, I may hardcode an exception to the rule in Reffy to tell it to ignore the existing IDL index and to rather create that index from the IDL fragments (which should work because the fragment is correctly flagged with `export` in the generated draft).

**Comment by foolip** [comment]
Is there a but filed against the SVG spec itself? Until now I thought the bug was with reffy, so perhaps the editors don't even know about all the fun we've been having here.

**Comment by tidoust** [comment]
Bug was indeed in the way the SVG spec was generated. Now fixed so closing this issue!

**Comment by foolip** [comment]
Ah, cool!
