### ISSUE TITLE
Missing SVG Presentation Attributes

### ISSUE THREAD

**Issue by pyoor** [tidoust/reffy#136]
I noticed that Reffy isn't parsing the SVG presentation attributes.  Since these are also valid CSS properties, shouldn't they be included as well?

**Comment by tidoust** [comment]
Could you give an example of a CSS property defined in the SVG spec that Reffy doesn't parse?

The CSS dump extracted from the SVG spec includes properties such as `cx`, `cy`, and `vector-effect` in particular:
https://github.com/tidoust/reffy-reports/blob/master/whatwg/css/SVG.json

Other [properties with a presentation attributes](https://svgwg.org/svg2-draft/single-page.html#styling-PresentationAttributes) seem to be defined in other specs.

Or would you be willing to see the list of CSS properties with a corresponding presentation attribute in the extract?

**Comment by pyoor** [comment]
My apologies but it looks like I was basing this on the fact that extract-cssdfn fails to produce any results for the SVG spec at https://www.w3.org/TR/SVG2/.  It appears that crawl-specs uses the editor's draft instead (https://svgwg.org/svg2-draft/).

As for the output, the current format provides everything that I need.  Thanks!
