### ISSUE TITLE
Extracted IDL for generic-sensor.idl includes snippets not in spec

### ISSUE THREAD

**Issue by foolip** [tidoust/reffy#140]
https://github.com/tidoust/reffy-reports/blob/master/w3c/idl/generic-sensor.idl
https://github.com/tidoust/reffy-reports/blob/master/whatwg/idl/generic-sensor.idl

These IDL files say they're extracted from https://w3c.github.io/sensors/, but after `MockSensorReadingValues` the content isn't from that spec:
```webidl
dictionary AmbientLightReadingValues {
  required double? illuminance;
};

dictionary AccelerometerReadingValues {
  required double? x;
  required double? y;
  required double? z;
};

dictionary LinearAccelerationReadingValues : AccelerometerReadingValues {
};

dictionary GravityReadingValues : AccelerometerReadingValues {
};

dictionary GyroscopeReadingValues {
  required double? x;
  required double? y;
  required double? z;
};

dictionary MagnetometerReadingValues {
  required double? x;
  required double? y;
  required double? z;
};

dictionary UncalibratedMagnetometerReadingValues {
  required double? x;
  required double? y;
  required double? z;
  required double? xBias;
  required double? yBias;
  required double? zBias;
};

dictionary AbsoluteOrientationReadingValues {
  required FrozenArray<double>? quaternion;
};

dictionary RelativeOrientationReadingValues : AbsoluteOrientationReadingValues {
};

dictionary GeolocationReadingValues {
  required double? latitude;
  required double? longitude;
  required double? altitude;
  required double? accuracy;
  required double? altitudeAccuracy;
  required double? heading;
  required double? speed;
};

dictionary ProximityReadingValues {
  required double? distance;
  required double? max;
  required boolean? near;
};
```

This also duplicates definitions in other files like ambient-light.idl which is how I noticed this.

The changes came in https://github.com/tidoust/reffy-reports/commit/252048281fc89c19a816640a3b52001c87405c02 and there might be some connection to https://github.com/w3c/sensors/commit/a5d943b02a2184029f3e25a53a095a2e93a6d829, but I'm not sure.

@Honry @anssiko FYI

**Comment by anssiko** [comment]
These dicts were landed in w3c/sensors as an interim solution before being moved to their final destination in downstream specs (=concrete sensors extending w3c/sensors).

When @dontcallmedom-bot does its next reffy run, these should be fixed I believe.

**Comment by foolip** [comment]
@dontcallmedom https://github.com/tidoust/reffy-reports/blob/master/w3c/idl/generic-sensor.idl hasn't been updated yet, do you know why?

**Comment by dontcallmedom** [comment]
@foolip the server on which we run reffy has been misbehaving for the past few weeks, and we haven't found the time to investigate why so far. @tidoust was planning to look at getting it to run in a travis instance instead.

**Comment by foolip** [comment]
That would be great, much easier to check the logs and see what might be going wrong.

**Comment by tidoust** [comment]
I believe this issue was merely due to the crawler failing to run on the server over and over again, and thus failing to update the IDL files. Things are back to normal now, so closing.
