### ISSUE TITLE
Strip `webappsec-` from filenames

### ISSUE THREAD

**Issue by foolip** [tidoust/reffy#142]
https://github.com/tidoust/reffy-reports/commit/cc0a43d1f28cafa83f4a005fb4c7c6d32c24efcb renamed feature-policy.idl to webappsec-feature-policy.idl based on the new spec URL.

However, it seems a virtual certainty that the eventual shortname will be feature-policy, because the URL if any will be http://w3.org/TR/feature-policy/ and not http://w3.org/TR/webappsec-feature-policy/.

Flip-flopping the name back and forth would be frustrating, and there aren't any other files in reffy-reports with this prefix.

My suggestion, therefore, is to strip `webappsec-` as a prefix.

**Comment by foolip** [comment]
@tidoust

**Comment by foolip** [comment]
@dontcallmedom do you think this would make sense?

**Comment by dontcallmedom** [comment]
absolutely; can you submit a pull request to that effect? if not, I'll try to look into it later

**Comment by foolip** [comment]
At what level should this be done? When determining a shortname from URL, or when making a filename from the shortname? Code pointers? :)

**Comment by dontcallmedom** [comment]
I would say in getShortname - https://github.com/tidoust/reffy/blob/f08fd79a4e294590d4844c0308b7e2a2dfc3a754/src/cli/crawl-specs.js#L401

**Comment by foolip** [comment]
Do you know if the `if (spec.shortname)` branch will be taken, or if this needs to go inside `if (githubMatch)`?

**Comment by dontcallmedom** [comment]
Ì think the one you care about is `githubMatch` - `spec.shortname` addresses specs that have already hit TR and have thus the shortname `TR/foo`. IIUC, the case we're dealing with is specs that haven't reached FPWD yet, and thus are only known by their editors draft github URL.
