### ISSUE TITLE
Failing to parse lots of specs

### ISSUE THREAD

**Issue by Ms2ger** [tidoust/reffy#144]
> The following network or parsing error occurred: `TypeError: Cannot read property 'version-history' of undefined TypeError: Cannot read property 'version-history' of undefined at fetch.then.then.s (/home/dom/github.com/reffy/src/lib/util.js:312:34) at <anonymous> at process._tickCallback (internal/process/next_tick.js:189:7)`
>
> Reffy could not render this specification as a DOM tree and cannot say anything about it as a result. In particular, it cannot include content defined in this specification in the analysis of other specifications crawled in this report.

on 7 of the first 10 specs in https://tidoust.github.io/reffy-reports/whatwg/

**Comment by tidoust** [comment]
Reffy repeatedly fails to run on W3C's server for some reason (for multiple reasons apparently, the above error suggests the W3C API server refused to serve the request Reffy sent, but Reffy also fails with more obscure error messages in other cases). I have been swamped with other priorities for the time being, so haven't found the time to look into it yet, sorry about that. Will try to look into it tomorrow.

**Comment by Ms2ger** [comment]
No worries, just wanted to make sure you're aware

**Comment by tidoust** [comment]
Main cause of troubles has now been fixed and Reffy now produces daily reports again, with the exception of the HTML spec, whose crawl fails with a timeout on the W3C server (tracked in #145). I'm closing this issue as a result.
