### ISSUE TITLE
Add curly quotes to CSS grammar parser

### ISSUE THREAD

**Issue by tidoust** [tidoust/reffy#148]
The CSS grammar is unclear that curly quotes are correct, but most CSS specs now use them, so the parser should support them. See https://github.com/tidoust/reffy-reports/issues/31

**Comment by foolip** [comment]
@tabatkins would know if the use of these quotes in specs is correct, or if it's a replacement that Bikeshed makes but shouldn't.

**Comment by tabatkins** [comment]
Hm, I think this is a replacement that Bikeshed makes but shouldn't. It (correctly) uses curly-quotes when formatting property autolinks, but it shouldn't do the same for property-as-grammar-nonterminal; I think I just copypasted blindly. Will fix in a bit.

**Comment by tabatkins** [comment]
Fixed. CSS specs should all get updated in an hour or less.

**Comment by foolip** [comment]
Great, thanks Tab!

@tidoust, maybe this change can be reverted, or are there still specs using these quotes?

**Comment by tidoust** [comment]
There are still 4 property definitions that are using curly quotes, but these probably need to be fixed manually. Recording them here for now:
- The [`font` property](https://drafts.csswg.org/css-fonts/#propdef-font) in CSS Fonts Module Level 3
- The [`marker` property](https://svgwg.org/specs/markers/#MarkerShorthand) in SVG Markers
- The [`fill-opacity` property](https://svgwg.org/svg2-draft/painting.html#FillOpacity) and [`stroke-opacity` property](https://svgwg.org/svg2-draft/single-page.html#painting-StrokeOpacity) in SVG

The /TR/ versions of CSS specs still use curly quotes as well, but I don't think anyone's looking at these results and we don't even publish the CSS and IDL extracts from /TR/ specs to `reffy-reports`, so no big deal.

I'll revert the change.
