### ISSUE TITLE
Failures to extract IDL

### ISSUE THREAD

**Issue by dontcallmedom** [tidoust/reffy#15]
The following specs have IDL but it doesn't get extracted by `parse-webidl` (I haven't investigated why yet):
* [ ] https://w3c.github.io/mediacapture-image/
* [ ] https://w3c.github.io/mediacapture-depth/
* [ ] https://w3c.github.io/screen-orientation/
* [ ] https://w3c.github.io/webdriver/webdriver-spec.html
* [ ] https://w3c.github.io/requestidlecallback/
* [ ] https://w3c.github.io/presentation-api/
* [ ] https://w3c.github.io/resource-timing/
* [ ] https://w3c.github.io/navigation-timing/
* [ ] http://w3c.github.io/selection-api/

**Comment by dontcallmedom** [comment]
One more recent runs, I now have the following ones suspiciously without IDL:
* [ ] https://w3c.github.io/mediacapture-image/ has no IDL
* [ ] https://w3c.github.io/requestidlecallback/ has no IDL
* [ ]  https://w3c.github.io/performance-timeline/ has no IDL

**Comment by tidoust** [comment]
FYI, all 3 specs use the "markdown" format of ReSpec, which seems to bug jsdom (at least, the postProcess event handlers are never processed) and make the parsing time out after 30 seconds.

**Comment by tidoust** [comment]
OK, so [forwarding the window's console output to the Node.js/io/js console](https://github.com/tmpvar/jsdom#forward-a-windows-console-output-to-the-nodejsiojs-console) reveals the problem: ReSpec markdown processing uses `DOMParser` which is not (yet?) supported by jsdom, see: https://github.com/tmpvar/jsdom/issues/1341

**Comment by tidoust** [comment]
Follow-up to note that ReSpec only uses `DOMParser` in `core/utils`:
https://github.com/w3c/respec/blob/fce1b4aedcb4a569eb538488d9aa132567433735/js/core/utils.js#L226

It should be doable to use a custom build of ReSpec that falls back to another mechanism, e.g. the one described in:
https://developer.mozilla.org/en-US/docs/Web/API/DOMParser

**Comment by dontcallmedom** [comment]
For now, I'll just blacklist the said documents since their TR versions is acceptable

**Comment by dontcallmedom** [comment]
but there are other documents for which I don't know why they fail, e.g. https://w3c.github.io/mediacapture-fromelement/

**Comment by dontcallmedom** [comment]
https://w3c.github.io/encrypted-media/ has no IDL
 https://w3c.github.io/mediacapture-screen-share/ has no IDL
 https://w3c.github.io/mediacapture-fromelement/ has no IDL
 https://w3c.github.io/mediacapture-output/ has no IDL
 http://www.w3.org/TR/2008/REC-ElementTraversal-20081222/ has no IDL
 http://www.w3.org/TR/2011/WD-orientation-event-20111201/ has no IDL

optionnel :
 http://www.w3.org/TR/2011/WD-geolocation-API-v2-20111201/ has no IDL

**Comment by tidoust** [comment]
Crawler should now correctly extract the IDL for all of these specs. However, please note that some of them have IDL errors, so the IDL parser fails to turn that IDL content into a tree and rather reports an error:

* encrypted-media
* orientation-event
* geolocation-API-v2
* findtext (not mentioned above)
* mediaont-api (not mentioned above)
* WebIDL (not mentioned above)

**Comment by dontcallmedom** [comment]
thanks!
