### ISSUE TITLE
DeviceOrientationEvent IDL is stale

### ISSUE THREAD

**Issue by foolip** [tidoust/reffy#158]
https://github.com/tidoust/reffy-reports/blob/master/whatwg/idl/orientation-event.idl is from https://w3c.github.io/deviceorientation/spec-source-orientation.html but that's stale and points to https://w3c.github.io/deviceorientation/.

@tidoust @dontcallmedom what needs to change to make https://w3c.github.io/deviceorientation/ be scraped instead?

**Comment by dontcallmedom** [comment]
In this case, I think the best and simplest option is to avoid the URL breakage at the source - I've submitted a pull request to that effect https://github.com/w3c/deviceorientation/pull/81

**Comment by foolip** [comment]
But how do we end up visiting https://w3c.github.io/deviceorientation/spec-source-orientation.html? https://www.w3.org/TR/orientation-event/ links directly to https://w3c.github.io/deviceorientation/...

**Comment by dontcallmedom** [comment]
Good question - it looks like the [data in the W3C API](https://api.w3.org/specifications/orientation-event/versions/20190416) (API key needed) is outdated - I'll report the problem.

**Comment by dontcallmedom** [comment]
the underlying data has been closed, and it seems like this was a one-off problem, so the next run should have the right data

**Comment by foolip** [comment]
Great, thank you! Will this also rename the file to deviceorientation.idl, or will the TR shortname be used?

**Comment by dontcallmedom** [comment]
the default is to use the TR shortname IIRC, so I don't expect that to change

**Comment by dontcallmedom** [comment]
fixed in https://github.com/tidoust/reffy-reports/commit/38956a641800806ea1dea061185a6e3b6b041fc2#diff-daa2485b2fe42db2c431ac1bec9206f5

**Comment by foolip** [comment]
Excellent, thank you!
