### ISSUE TITLE
Keep dependencies up-to-date using dependabot

### ISSUE THREAD

**Issue by foolip** [tidoust/reffy#159]
reffy has a bunch of dependencies in package.json which are manually maintained.

In particular webidl2 is evolving quickly and often increases its major version, and getting these changes from webidl2 are important to supporting new Web IDL syntax.

My recommendation is to configure https://dependabot.com/ for this repository. https://github.com/foolip/mdn-bcd-collector/pull/140 is an example of what this can look like.

**Comment by foolip** [comment]
@tidoust

**Comment by foolip** [comment]
It has begun :) https://github.com/tidoust/reffy/pull/161

**Comment by foolip** [comment]
To have any confidence that the updates won't break everything it'll of course also be necessary to run some tests on PRs.

**Comment by tidoust** [comment]
Good point. I added Dependabot. Tests are definitely another missing block here.

Some of the updates may have to be ignored, at least for now. For instanc,e, we cannot bump JSDOM to its latest version beause Reffy [hooks into its `ResourceLoader.download` method](https://github.com/tidoust/reffy/blob/master/src/lib/jsdom-monkeypatch.js#L27). Last time I checked, this method had gone and there was no longer any way to plug a custom HTTP resource loader into JSDOM. We'll need to find a workaround.

**Comment by foolip** [comment]
Yep, leaving bump PRs open is fine. Or there are commands to tell dependabot to ignore certain versions, that's fine too.

**Comment by foolip** [comment]
Thanks for the quick action! Looking forward to the webidl2 upgrade... or maybe there won't be one because ^23.3.0 matches the most recent version? I guess so, package-lock.json says 23.8.1.

**Comment by tidoust** [comment]
`^23.3.0` matches the most recent version but is it the recommended way to reference libraries in `package.json` when Dependabot is running? That is, will Dependabot create a PR to update `package-lock.json` when 23.8.2 is out? Should we rather drop all `^` from `package.json`?
