### ISSUE TITLE
Extract terms defined with "data-export" attribute

### ISSUE THREAD

**Issue by tidoust** [tidoust/reffy#170]
Cross-reference links to terms defined in another spec should be limited to term definitions that are explicitly marked up as exported through a `data-export` attribute, since these terms represent the stable interface that authors are ready to support.

Reffy should extract these terms and their ID, and report an anomaly when a spec references a term that is not in the list of exported terms.

Note spec edition tools already automatically mark WebIDL terms with a  `data-export=""` attribute, so no need to treat them differently.

**Comment by dontcallmedom** [comment]
This was done in https://github.com/tidoust/reffy/pull/229
