### ISSUE TITLE
Use Puppeteer throughout instead of JSDOM

### ISSUE THREAD

**Issue by tidoust** [tidoust/reffy#196]
Since the latest version of Respec cannot run in JSDOM (see https://github.com/tidoust/reffy/pull/195), Reffy now de facto has [Puppeteer](https://github.com/GoogleChrome/puppeteer) as a dependency. We still use JSDOM to:
1. load specs (without running external scripts) to detect whether they use Respec. If not, the loaded spec is used as is. Otherwise it gets sent to `respecDocWriter`.
3. load Respec specs after generation

To reduce the number of dependencies and ease maintenance, it would probably be wise to use only one browser stack, namely through a hreadless browser such as Puppeteer. This would actually also simplify the logic, since we would just need to load each spec once and for all (Respec will just run directly within Puppeteer and we can simply work on the result). It could perhaps also help with the "crawl took too long" errors on the HTML spec that haven't completely disappeared.

**Comment by foolip** [comment]
Does this relate to https://github.com/tidoust/reffy/issues/30?

Is the only reason a real browser is needed because of ReSpec, and what information is only available after the scripts run? A whitespace change came up in https://github.com/web-platform-tests/wpt/pull/20383 and it'd be nice to just use the IDL fragments from the static HTML instead.

**Comment by tidoust** [comment]
> Does this relate to #30?

No. #30 was more about running Reffy entirely within a browser instead of as a Node.js program. But on top of being hard to achieve, that doesn't seem needed at all, and I don't think we'll ever get to that.

> Is the only reason a real browser is needed because of ReSpec, and what information is only available after the scripts run?

Reffy no longer runs external scripts for now in practice, so we don't necessarily need a real browser (we still need something that gives a DOM to ease extracting info from the HTML content).

We need the generated versions of ReSpec specs betcause Reffy checks things such as references that are generated by ReSpec and thus that do not appear in the source version.

I also prefer to check the spec that users see, not the spec that the author wrote, given that scripts can create side effects that the author may not have thought about. That said, I certainly understand that whitespace changes are useless and a waste of time from a WPT perspective.

**Comment by tidoust** [comment]
Done through PR #254.
