### ISSUE TITLE
Invalid IDL updates on Dec 30

### ISSUE THREAD

**Issue by stephenmcgruer** [tidoust/reffy#205]
We're seeing a bunch of automated reffy PRs in https://github.com/web-platform-tests/wpt which seem invalid and seem to have come from https://github.com/tidoust/reffy/commit/89d459537d25b1911ff6e0393f833527307c53be. They seem to prefix the word 'WebIDL' onto the generated idl.

Example: https://github.com/web-platform-tests/wpt/pull/20941, which changes:

- `partial interface Navigator {` --> `WebIDLpartial interface Navigator {`
- `[Exposed=Window] interface BatteryManager : EventTarget {` --> `WebIDL[Exposed=Window] interface BatteryManager : EventTarget {`

These then fail to parse in the IDL test harness, resulting in harness errors: https://wpt.fyi/results/battery-status/idlharness.https.window.html?diff&filter=ADC&run_id=404190005&run_id=406030001

**Comment by stephenmcgruer** [comment]
Update: this has now caused dozens of invalid pull requests to be opened against wpt :(. I'm still OOO, but will be looking tomorrow to disable the automated reffy puller (@foolip) and then close the invalid PRs.

**Comment by foolip** [comment]
@tidoust

**Comment by foolip** [comment]
It looks like https://github.com/tidoust/reffy-reports/commit/358e96559518cf016dc672e487b314930c70dd59 and https://github.com/tidoust/reffy-reports/commit/99832fa8b86048b1db7736e7d8b173ce5d08e940 are the commits that updated all IDL files, and this happened on Dec 30 using reffy commit 89d459537d25b1911ff6e0393f833527307c53be. However, that commit is from Dec 11 and appears in reffy-reports commit messages going back to then. So while a respec bump seems like a somewhat plausible cause for this, there's something more going on here...

**Comment by foolip** [comment]
[Here](https://github.com/tidoust/reffy-reports/commit/358e96559518cf016dc672e487b314930c70dd59/checks?check_suite_id=378499126) is the GitHub Actions run that pushed https://github.com/tidoust/reffy-reports/commit/99832fa8b86048b1db7736e7d8b173ce5d08e940, and [this](https://github.com/tidoust/reffy-reports/commit/358e96559518cf016dc672e487b314930c70dd59/checks?check_suite_id=378499126) is a run from before things went wrong.

All the versions that I can see in the logs are the same. The version of node installed isn't shown but it seems fairly unlikely that a change in the LTS version of node would have caused this.

**Comment by foolip** [comment]
Confirmed locally that the same problem occurs with commit 255cd97ba08aa8d5ccbe1150b0ad2fe1ceee5534, renaming this issue to reflect.

**Comment by foolip** [comment]
Problem seems to be with specs that include https://www.w3.org/Tools/respec/respec-w3c, and the changes from https://github.com/w3c/respec/pull/2663. It'll be necessary to exclude the IDL header to fix this.

**Comment by foolip** [comment]
Fix up in https://github.com/tidoust/reffy/pull/208.
