### ISSUE TITLE
List specs that depend on a given spec

### ISSUE THREAD

**Issue by chaals** [tidoust/reffy#26]
A common problem when messing with some API is to know who is a consumer.

In general, that's pretty much unanswerable. But it would be helpful if reffy would at least provide a simple list of specs that depend on X, so if you are changing X you can let the spec people who might be upset know…

**Comment by tidoust** [comment]
@chaals First, thanks for the suggestion! @dontcallmedom and I managed to get some work done on Reffy this week and Reffy can now produce a dependencies report. Closing this as a result.

By definition, Reffy will only report on incoming links to a specification from specifications it knows about. In particular, note that we have retained an IDL focus for now: the crawl does not include non-IDL specs (many CSS specs are missing for instance).
