### ISSUE TITLE
Build spec list (semi-?)automatically

### ISSUE THREAD

**Issue by dontcallmedom** [tidoust/reffy#27]
Starting from a manually curated list of specs is not ideal, since new specs emerge all the time, and old specs get replaced by newer versions.

One approach is to derive the list automatically from https://platform.html5.org/ and/or https://www.w3.org/standards/techs/js#w3c_all ; another might be to extract specs from caniuse or chrome platform status.

We would probably want a blacklist of specs to ignore

**Comment by tidoust** [comment]
Doing some house-keeping here. We have a semi-automatic mechanism in place to detect new specs. That could be improved, for sure, but seems good enough for now. Closing this issue as a result.
