### ISSUE TITLE
Bug when using completeWithInfoFromW3CApi with key as arg

### ISSUE THREAD

**Issue by pyoor** [tidoust/reffy#309]
The change implemented e90c4cb9b7cff11692019106c2bf4179fb66127d breaks completeWithInfoFromW3CApi by checking that spec is a string.  This is incorrect as later references to spec in this function treat it as an object.

https://github.com/tidoust/reffy/blob/c579ea60d52e3a141f5e8d8d30b85a33a5e7c098/src/lib/util.js#L369

I assume that the fix was meant to check that key is a string and not spec.

**Comment by tidoust** [comment]
Oops. Thanks! Fixed in https://github.com/tidoust/reffy/commit/138a4f530733f5e4de3d8b9ad9118e805d0154e9

FWIW, we will soon drop this function entirely as part of the switch to [browser-specs](https://github.com/w3c/browser-specs/) to determine the list of specs to crawl and their info.
