### ISSUE TITLE
No mathml spec in reffy?

### ISSUE THREAD

**Issue by stephenmcgruer** [tidoust/reffy#370]
Apologies if I'm missing something really obvious, but it came up in https://chromium-review.googlesource.com/c/chromium/src/+/2317813 that the mathml spec (https://mathml-refresh.github.io/mathml-core/, specifically https://mathml-refresh.github.io/mathml-core/#dom-mathmlelement in this case) was missing from reffy's reports (or at least hasn't been imported into WPT).

Based on https://github.com/w3c/browser-specs/search?q=mathml&type=Code, it appears to be in w3c/browser-specs, but I can't find any mention of mathml here other than https://github.com/tidoust/reffy/pull/312, which seems to imply it will be added but maybe wasn't?

**Comment by tidoust** [comment]
I see a [PR on MathML in WPT](https://github.com/web-platform-tests/wpt/pull/24060) with a "do not merge yet" label that I believe you added ;)

The IDL extracts produced by Reffy contain a [mathml-core.idl](https://github.com/tidoust/reffy-reports/blob/master/ed/idl/mathml-core.idl) file in particular. Or are you looking for something else?

**Comment by stephenmcgruer** [comment]
*head* --> *desk*, *head* --> *desk*

-_-.

(Shame-close)
