### ISSUE TITLE
Automate error notifications

### ISSUE THREAD

**Issue by tidoust** [tidoust/reffy#55]
To be useful, Reffy should be run on a recurring basis, e.g. once per week, and report via email on the diff since previous version. To avoid spamming our inboxes, the report should only be sent when there is something new and interesting, typically when a new anomaly is detected.

**Comment by dontcallmedom** [comment]
I've set up the following script to be run in a cron job:
```bash
#!/bin/bash


cd  ~/github.com/reffy
git pull origin master
xvfb-run node crawl-specs.js ./specs-whatwg.json results-whatwg.json

node study-specs.js ./results-whatwg.json perspec > report.new

# has it changed since last time?
if (diff -u report.orig report.new |grep -v "^\+- Date:"|grep "^\+" > /dev/null) ;
   then 
      diff report.orig report.new  | mail -s "Reffy update report" dom@w3.org fd@w3.org
      cp report.new report.orig
fi
```

Closing this

**Comment by tidoust** [comment]
Re-opening the issue as I added a "diff" generator to the study tool in https://github.com/tidoust/reffy/commit/fc994905cbae39b3ee8d42623db292caf9eddf9a to produce a diff (in Markdown).

From the cron job, you should be able to just call `npm run all` (or `npm run w3c` and `npm run whatwg` and the reports will now include:

- `diff.md`: A complete diff between the newly generated crawl report and the latest crawl report published on GitHub
- `diffnew.md`: A diff between the newly generated crawl report and the latest crawl report published on GitHub that only (or almost only for now) reports on new anomalies.

**Comment by tidoust** [comment]
Note that even with `diffnew.md`, you'll probably still want a way to detect when the diff is empty. Essentially, if you exclude the first 3 header lines in the Markdown file and empty lines, the diff is empty when the file is empty.

**Comment by dontcallmedom** [comment]
updated accordingly, and seems to work as expected, so closing again
