### ISSUE TITLE
Publish report automatically

### ISSUE THREAD

**Issue by dontcallmedom** [tidoust/reffy#62]
We should run the scripts to create the report on a regular basis and publish it for ease of use.

I can fairly easily add this to my reporting script (#55), but the question is whether we publish it in this repo (e.g. on a `gh-pages` branch) or in a separate repo as for webidlpedia.

**Comment by tidoust** [comment]
It seems easier initially to publish reports within this repo, typically within the `report` folder.

Note I would rather publish it in the `master` branch (having that branch be the one used for GitHub Pages) instead of within a separate `gh-pages` branch.

**Comment by dontcallmedom** [comment]
The reason I suggested a separate branch or repo is because I dislike mixing built files with their building scripts; but I can live with it.

**Comment by tidoust** [comment]
Right, I get that. The reason I suggested the same branch is because I dislike repos that have different branches for very different purpose. I'm fine with a separate repo, it's just that we might need to copy over the `reffy.js` and other files referenced by the HTML report.

**Comment by tidoust** [comment]
Upon further consideration, if the report gets updated automatically, publication is going to mess the history of that repository, so a separate repo looks better. It would also allow to store the results of the crawl (the JSON outcome) on top of just the HTML report.

I created [reffy-reports](https://github.com/tidoust/reffy-reports) for that. GitHub Pages enabled on the `master` branch.

**Comment by tidoust** [comment]
Build scripts in `package.json` updated accordingly. They now create the appropriate list of files in the `reports/w3c/` and `reports/whatwg` folders.

**Comment by dontcallmedom** [comment]
I've updated the cron job accordingly - closing
