### ISSUE TITLE
Loop through specs to build dependency graph

### ISSUE THREAD

**Issue by tidoust** [tidoust/reffy#7]
Once the list of specs is available (#5), create a tool that loops through these specs and apply the right references extractor (#1, #2, #6) to create the graph of dependencies in some JSON structure.

**Comment by dontcallmedom** [comment]
one thing to watch out: at least for the HTML spec (but maybe others?), we need to apply the extractors on the "single page" version.

**Comment by tidoust** [comment]
Or apply the extractors to the right page. For instance, The IDL appears twice in HTML5: in the main body of the spec and as an appendix. That appendix is also a separate page.

For references, same thing for CSS2.1, SMIL, although I'm not sure there are many APIs that are multi-page documents on top of HTML5.

**Comment by tidoust** [comment]
Closing this issue as the crawler has been in place for a few commits now.
