### ISSUE TITLE
Ignore `Window` for report on missing references?

### ISSUE THREAD

**Issue by dontcallmedom** [tidoust/reffy#72]
With `Exposed=Window` becoming required for interfaces, reffy will want to see all specs have a reference to the HTML spec (where `Window` is formally defined).

That feels kind-of noisy - both to expect specs to add the reference just for this, and reffy to complain for all specs that don't.

I think we might want to make an exception in the reporting made by reffy to ignore `Window` as a source of normative dependency.

**Comment by tidoust** [comment]
Exception to the rule added. Reffy no longer reports on `Window` as a source of normative dependency when it only appears in `Exposed=Window` statements.
