### ISSUE TITLE
Add link to GitHub repository when known

### ISSUE THREAD

**Issue by tidoust** [tidoust/reffy#74]
via @tobie

Specref now returns the repository associated with a specification, through [some hardcoded logic](https://github.com/tobie/specref/blob/master/scripts/github.js) and possible manual updates afterwards.

It would be useful to link to GitHub repositories of specs that appear in Reffy's reports, e.g. to ease reporting of issues.

Specref information can be retrieved through the [reverse lookup endpoint](https://github.com/tobie/specref#reverse-lookup)

**Comment by tobie** [comment]
edDraft would be another useful one, too.

**Comment by tidoust** [comment]
Both the ED and the GitHub repository should be returned in Reffy's reports from now on.
I also added the latest publication status for W3C specs.

**Comment by tobie** [comment]
\o/
